application: hackthology
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /imgs
  static_dir: imgs

- url: /script
  static_dir: script

# - url: /resume
#   script: index.py
# - url: /about
#   script: index.py
#
- url: /.*
  script: index.py
